### ISSUE TITLE
Enhancing Weather Page (UI and UX) 

### ISSUE THREAD

**Issue by sajalbatra** [FarmHubb/FarmHub#49]
Is your feature request related to a problem? Please describe.

Currently, the weather page has a basic UI and lacks visually appealing design. Users often find it challenging to navigate and interpret the displayed information.

Describe the solution you'd like

I would like to enhance the weather page's user interface to make it more visually pleasing and user-friendly. The improved design should provide a clear and intuitive layout, making it easier for users to access weather information at a glance. Additionally, I suggest adding interactive elements to allow users to customize the displayed data and view different weather metrics based on their preferences.

Describe alternatives you've considered

One alternative would be to keep the current weather page as is. However, this might result in user frustration due to the unintuitive design and lack of interactivity.

Current Weather Page

I'm confident that implementing these changes will significantly enhance the user experience and provide valuable insights into the weather conditions. Looking forward to your feedback and collaboration on this exciting enhancement!

**Comment by sajalbatra** [comment]
Will try to complete it soon Please don't remove the issue from me as i am also working on my personal project side by side

**Comment by marshadkhn** [comment]
Hey @sajalbatra
Please make sure that your changes sync with the current UI and colors and use material UI or the raw styling
