### ISSUE TITLE
Updating Readme file

### ISSUE THREAD

**Issue by shubhamgarg21156** [FarmHubb/FarmHub#53]
There is a spelling mistake in the title of the project mentioned in the readme. I want to update the same. 

1. Go to 'Readme.md'
2. Check the title name.

**Screenshot**:
![image](https://github.com/FarmHubb/FarmHub/assets/66112766/624d2624-84ea-4b91-8643-7d0568ce335e)

**Comment by marshadkhn** [comment]
Thanks for noticing :)

**Comment by shubhamgarg21156** [comment]
@marshadkhn Please review my PR. 

**PR link:**
https://github.com/FarmHubb/FarmHub/pull/54
